export type RecommendationCategory = "hotels" | "routes" | "restaurants" | "attractions";

export interface RecommendationItem {
  id: string;
  title: string;
  description: string;
  reason: string;
  tags: string[];
  priceLevel: "$" | "$$" | "$$$";
}

export type RecommendationGroups = Record<RecommendationCategory, RecommendationItem[]>;

export interface RecommendationRequest {
  destination: string;
  interests?: string[];
  budget?: number;
}

export interface RecommendationResponse {
  destination: string;
  normalizedDestination: string;
  source: "static-demo-data";
  disclaimer: string;
  recommendations: RecommendationGroups;
}

const disclaimer = "Recommendations are static demo data and are not generated by real AI.";

const fallbackRecommendations: RecommendationGroups = {
  hotels: [
    {
      id: "fallback-hotel-1",
      title: "Harbor Light Boutique Stay",
      description: "A centrally located hotel with flexible check-in and easy transit access.",
      reason: "Good default base for first-time visitors.",
      tags: ["central", "transit", "comfort"],
      priceLevel: "$$"
    },
    {
      id: "fallback-hotel-2",
      title: "Old Town Guesthouse",
      description: "A compact stay near walkable neighborhoods and local cafes.",
      reason: "Balances value with neighborhood character.",
      tags: ["budget", "walkable", "local"],
      priceLevel: "$"
    }
  ],
  routes: [
    {
      id: "fallback-route-1",
      title: "Arrival Loop",
      description: "Airport transfer, hotel check-in, and a short evening walk near the hotel.",
      reason: "Keeps the first day low-friction after travel.",
      tags: ["arrival", "easy", "orientation"],
      priceLevel: "$"
    },
    {
      id: "fallback-route-2",
      title: "Market to Viewpoint Trail",
      description: "Start at a morning market, continue through a historic quarter, and finish at a skyline viewpoint.",
      reason: "Combines food, culture, and a memorable photo stop.",
      tags: ["food", "culture", "views"],
      priceLevel: "$"
    }
  ],
  restaurants: [
    {
      id: "fallback-restaurant-1",
      title: "Corner Table Kitchen",
      description: "Seasonal plates with local ingredients and relaxed service.",
      reason: "Approachable dinner option for mixed preferences.",
      tags: ["local", "dinner", "seasonal"],
      priceLevel: "$$"
    },
    {
      id: "fallback-restaurant-2",
      title: "Station Noodle Bar",
      description: "Fast, casual bowls close to major transit.",
      reason: "Convenient for a packed sightseeing day.",
      tags: ["quick", "lunch", "transit"],
      priceLevel: "$"
    }
  ],
  attractions: [
    {
      id: "fallback-attraction-1",
      title: "City Story Museum",
      description: "A compact museum that explains the destination's history and neighborhoods.",
      reason: "Helpful early context for the rest of the trip.",
      tags: ["culture", "history", "rainy-day"],
      priceLevel: "$"
    },
    {
      id: "fallback-attraction-2",
      title: "Riverside Promenade",
      description: "A scenic pedestrian route with cafes, public art, and sunset views.",
      reason: "Easy, flexible activity that works for most schedules.",
      tags: ["views", "walk", "free"],
      priceLevel: "$"
    }
  ]
};

const destinationRecommendations: Record<string, RecommendationGroups> = {
  tokyo: {
    hotels: [
      {
        id: "tokyo-hotel-1",
        title: "Shinjuku Lantern House",
        description: "A modern hotel near late-night food streets and major rail connections.",
        reason: "Ideal for travelers who want easy transit and energetic evenings.",
        tags: ["transit", "nightlife", "food"],
        priceLevel: "$$"
      },
      {
        id: "tokyo-hotel-2",
        title: "Asakusa Ryokan Annex",
        description: "A calm traditional-style stay close to temples and river walks.",
        reason: "Matches culture-focused trips with a quieter home base.",
        tags: ["culture", "traditional", "quiet"],
        priceLevel: "$$"
      }
    ],
    routes: [
      {
        id: "tokyo-route-1",
        title: "Market, Shrine, Skyline",
        description: "Tsukiji Outer Market, Hamarikyu Gardens, river cruise, and Tokyo Skytree.",
        reason: "A balanced first full day with food, history, and views.",
        tags: ["food", "culture", "views"],
        priceLevel: "$$"
      },
      {
        id: "tokyo-route-2",
        title: "Harajuku to Shibuya Drift",
        description: "Meiji Shrine, Takeshita Street, Omotesando, and Shibuya Crossing.",
        reason: "Great for shopping, street culture, and iconic city energy.",
        tags: ["shopping", "culture", "walk"],
        priceLevel: "$"
      }
    ],
    restaurants: [
      {
        id: "tokyo-restaurant-1",
        title: "Kanda Ramen Counter",
        description: "A compact counter-service ramen shop with rotating regional broths.",
        reason: "Static pick for a classic Tokyo food moment.",
        tags: ["food", "ramen", "casual"],
        priceLevel: "$"
      },
      {
        id: "tokyo-restaurant-2",
        title: "Ebisu Yakitori Room",
        description: "Grilled skewers, small plates, and a relaxed neighborhood setting.",
        reason: "Works well for a social dinner after sightseeing.",
        tags: ["dinner", "local", "food"],
        priceLevel: "$$"
      }
    ],
    attractions: [
      {
        id: "tokyo-attraction-1",
        title: "Senso-ji Temple",
        description: "Tokyo's oldest temple with a lively shopping street approach.",
        reason: "Strong culture match and easy to combine with Asakusa.",
        tags: ["culture", "history", "landmark"],
        priceLevel: "$"
      },
      {
        id: "tokyo-attraction-2",
        title: "teamLab Borderless",
        description: "Immersive digital art installations with timed entry.",
        reason: "A memorable indoor attraction for design and art interests.",
        tags: ["art", "indoor", "modern"],
        priceLevel: "$$"
      }
    ]
  },
  paris: {
    hotels: [
      {
        id: "paris-hotel-1",
        title: "Canal Saint-Martin Atelier",
        description: "A design-forward stay near cafes, boutiques, and canal walks.",
        reason: "Good for food and neighborhood exploration.",
        tags: ["food", "boutique", "walkable"],
        priceLevel: "$$"
      },
      {
        id: "paris-hotel-2",
        title: "Left Bank Reading Room",
        description: "A quiet hotel close to bookshops, gardens, and museums.",
        reason: "Supports culture-heavy itineraries without feeling rushed.",
        tags: ["culture", "museums", "quiet"],
        priceLevel: "$$$"
      }
    ],
    routes: [
      {
        id: "paris-route-1",
        title: "Louvre to Latin Quarter Walk",
        description: "Louvre courtyard, Pont des Arts, Notre-Dame exterior, and Latin Quarter lanes.",
        reason: "Classic Paris orientation with flexible museum time.",
        tags: ["culture", "history", "walk"],
        priceLevel: "$"
      },
      {
        id: "paris-route-2",
        title: "Montmartre Morning Climb",
        description: "Coffee near Abbesses, Sacre-Coeur, artist squares, and hillside viewpoints.",
        reason: "Combines atmosphere, views, and casual cafe stops.",
        tags: ["views", "cafes", "art"],
        priceLevel: "$"
      }
    ],
    restaurants: [
      {
        id: "paris-restaurant-1",
        title: "Rue des Martyrs Bistro",
        description: "A compact bistro with a seasonal chalkboard menu.",
        reason: "Reliable static pick for a neighborhood dinner.",
        tags: ["food", "bistro", "dinner"],
        priceLevel: "$$"
      },
      {
        id: "paris-restaurant-2",
        title: "Marais Falafel Window",
        description: "Fast, filling lunch in a lively historic district.",
        reason: "Keeps the day moving between attractions.",
        tags: ["lunch", "quick", "budget"],
        priceLevel: "$"
      }
    ],
    attractions: [
      {
        id: "paris-attraction-1",
        title: "Musee d'Orsay",
        description: "Impressionist masterpieces inside a converted railway station.",
        reason: "Strong art and culture match.",
        tags: ["art", "culture", "museum"],
        priceLevel: "$$"
      },
      {
        id: "paris-attraction-2",
        title: "Luxembourg Gardens",
        description: "Formal gardens with chairs, fountains, and slow afternoon energy.",
        reason: "A restorative pause between denser museum stops.",
        tags: ["parks", "relax", "free"],
        priceLevel: "$"
      }
    ]
  },
  "new york": {
    hotels: [
      {
        id: "nyc-hotel-1",
        title: "NoMad Transit Hotel",
        description: "A central stay with quick subway access downtown and uptown.",
        reason: "Good base for a packed multi-neighborhood itinerary.",
        tags: ["central", "transit", "city"],
        priceLevel: "$$$"
      },
      {
        id: "nyc-hotel-2",
        title: "Williamsburg Warehouse Rooms",
        description: "Loft-inspired rooms near music venues and waterfront parks.",
        reason: "Fits food, nightlife, and skyline-view interests.",
        tags: ["nightlife", "views", "food"],
        priceLevel: "$$"
      }
    ],
    routes: [
      {
        id: "nyc-route-1",
        title: "High Line to Village",
        description: "Chelsea Market, High Line, West Village streets, and Washington Square Park.",
        reason: "A walkable route with food, architecture, and people-watching.",
        tags: ["food", "walk", "architecture"],
        priceLevel: "$"
      },
      {
        id: "nyc-route-2",
        title: "Brooklyn Bridge Sunrise",
        description: "Early bridge walk, Dumbo photo stop, and ferry ride back to Manhattan.",
        reason: "Efficient route for skyline views and iconic photos.",
        tags: ["views", "landmark", "photo"],
        priceLevel: "$"
      }
    ],
    restaurants: [
      {
        id: "nyc-restaurant-1",
        title: "Lower East Side Dumpling Stop",
        description: "Casual dumplings and noodles near galleries and vintage shops.",
        reason: "Budget-friendly food stop with neighborhood texture.",
        tags: ["food", "budget", "casual"],
        priceLevel: "$"
      },
      {
        id: "nyc-restaurant-2",
        title: "Greenwich Pasta Bar",
        description: "House-made pasta in a compact dining room off a quiet block.",
        reason: "Good celebratory dinner without leaving the core route.",
        tags: ["dinner", "date-night", "food"],
        priceLevel: "$$$"
      }
    ],
    attractions: [
      {
        id: "nyc-attraction-1",
        title: "The Met",
        description: "A vast museum collection spanning art, design, and global history.",
        reason: "A strong anchor for culture-focused travelers.",
        tags: ["museum", "culture", "art"],
        priceLevel: "$$"
      },
      {
        id: "nyc-attraction-2",
        title: "Top of the Rock",
        description: "Observation deck with open views of Central Park and the Empire State Building.",
        reason: "Reliable skyline moment for a short trip.",
        tags: ["views", "landmark", "photo"],
        priceLevel: "$$$"
      }
    ]
  }
};

function normalizeDestination(destination: string): string {
  return destination.trim().toLowerCase().replace(/\s+/g, " ");
}

function scoreItem(item: RecommendationItem, interests: string[]): number {
  if (interests.length === 0) {
    return 0;
  }

  const normalizedTags = new Set(item.tags.map((tag) => tag.toLowerCase()));
  return interests.reduce((score, interest) => score + (normalizedTags.has(interest.toLowerCase()) ? 1 : 0), 0);
}

function prioritizeByInterests(items: RecommendationItem[], interests: string[]): RecommendationItem[] {
  return [...items].sort((left, right) => scoreItem(right, interests) - scoreItem(left, interests));
}

export function getRecommendations(request: RecommendationRequest): RecommendationResponse {
  const normalizedDestination = normalizeDestination(request.destination || "default");
  const interests = request.interests ?? [];
  const baseRecommendations = destinationRecommendations[normalizedDestination] ?? fallbackRecommendations;

  return {
    destination: request.destination,
    normalizedDestination,
    source: "static-demo-data",
    disclaimer,
    recommendations: {
      hotels: prioritizeByInterests(baseRecommendations.hotels, interests),
      routes: prioritizeByInterests(baseRecommendations.routes, interests),
      restaurants: prioritizeByInterests(baseRecommendations.restaurants, interests),
      attractions: prioritizeByInterests(baseRecommendations.attractions, interests)
    }
  };
}
